### ISSUE TITLE
Crashes when using with Buildcraft 6.3.1

### ISSUE THREAD

**Issue by da3dsoul** [da3dsoul/Additional-Buildcraft-Objects#9]
Quoted from Abestanis on fork.

Hi, I really like this mod and was really happy to see, that there is someone who not only just continues development, but also has added some quite cool new things which helps this mod to move further.

I myself as a developer appreciate the time and effort you put into maintaining this code and adding your own ideas. I just want you to know that there are people who use this mod and enjoy the outcome your hard work.

In this context, I want to ask you for an update for the newest buildcraft release. If you start minecraft with the latest buildcraft and your mod, you'll get a NoClassDefFoundError.
Can you please try to fix this issue, so we can continue to enjoy your great mod!

**Comment by da3dsoul** [comment]
https://github.com/da3dsoul/Additional-Buildcraft-Objects 
Go to release section and download it. place it in the mods folder. It works with BC6.3.1.

**Comment by Abestanis** [comment]
I'm really sorry, I did not read the project description of your old repository and had not realized that you had made a new repository. I apologize for this mistake of mine!

I have also tested it and found it working fine.

**Comment by da3dsoul** [comment]
Good to hear. I was like, "How has no one posted yet if it is broken?"
